# Generated by Django 5.2.15 on 2026-07-02 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UrunStok',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Ürün Adı')),
                ('stock_quantity', models.IntegerField(default=0, verbose_name='Stok Miktarı')),
                ('critical_threshold', models.IntegerField(default=10, verbose_name='Kritik Eşik')),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Alış Fiyatı (₺)')),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Satış Fiyatı (₺)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Son Güncelleme')),
            ],
            options={
                'verbose_name': 'Ürün Stok',
                'verbose_name_plural': 'Ürün Stoklar',
                'ordering': ['-updated_at'],
            },
        ),
    ]
