# Generated by Django 5.2.15 on 2026-07-03 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='urunstok',
            name='unit',
            field=models.CharField(blank=True, help_text='Örn: Adet, Kilo, Koli vb.', max_length=50, null=True, verbose_name='Birim'),
        ),
    ]
