# Generated by Django 5.2.15 on 2026-07-03 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depo', '0002_urunstok_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='urunstok',
            name='group',
            field=models.CharField(blank=True, help_text='Örn: GIDA, HİJYEN, TEMİZLİK', max_length=150, null=True, verbose_name='Grubu'),
        ),
    ]
